version: 0.0
# 선택한 ec2 가 window server가 아니라면 linux를 적어준다.
os: linux
files:
# source는 프로젝트 기준, destination은 instance 기준으로 입력해주고, 
# source가 destination안에 복사됨
  - source: /
    destination: /usr/share/nginx/html/
